### ISSUE TITLE
Weird sites to monitor

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/citizen-onboard#34]
- NJ: https://oneapp.dhs.state.nj.us/Forms/SignIn/frmStart.aspx
- NV: https://idcnv.dwss.nv.gov:8443/nidp/idff/sso?id=17&sid=6&option=credential&sid=6

**Comment by lippytak** [comment]
This seemed to work for NV:

```
{
    "1": {
        "get": "https://accessnevada.dwss.nv.gov/NV-EAPPWEB/EAPPServlet?USER_REQUEST=PR_MAIN_PAGE&USER_ACTION=LOGIN&GUI_ENV_DB_NUMBER=W100DP1"
    },
    "2": {
        "assert_in_content": "Username"
    }
}
```

But this does NOT seem to work for NJ:

```
{
    "1": {
        "get": "https://oneapp.dhs.state.nj.us/Forms/SignIn/frmNewApplication.aspx"
    },
    "2": {
        "assert_in_content": "User Id"
    }
}
```

**Comment by pingometer** [comment]
# NV

The anchor link on the web page sends you through https://accessnevada.dwss.nv.gov/NV-EAPPWEB/EAPPServlet?USER_REQUEST=PR_MAIN_PAGE&USER_ACTION=LOGIN&GUI_ENV_DB_NUMBER=W100DP1 before it redirects to https://idcnv.dwss.nv.gov:8443/nidp/idff/sso?id=17&sid=6&option=credential&sid=6.

If you attempt to directly access https://idcnv.dwss.nv.gov:8443/nidp/idff/sso?id=17&sid=6&option=credential&sid=6 without passing through the first link, you get an empty page (no content).

The monitor was adjusted to use the first URL and it checks correctly now.

**Comment by pingometer** [comment]
# NJ

This is related to a client-side (JavaScript) alert that prevents the monitor from continuing the check (see attached).

Our transaction monitor will now accept popups like this, by default.

![screen shot 2015-01-18 at 10 14 35 pm](https://cloud.githubusercontent.com/assets/7914492/5797156/9bd3bbfe-9f69-11e4-8494-a8a4e33d5773.png)

**Comment by alanjosephwilliams** [comment]
Thanks @pingometer!

**Comment by pingometer** [comment]
You bet! We think what you're doing is really cool - happy to help if you need anything else.
