### ISSUE TITLE
Public facing page for "StatusBoard"

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/citizen-onboard#35]
Our current thinking is that "StatusBoard" will launch as a CitizenOnboard branded project.

An effective launch requires landing page that communicates what StatusBoard is, why its important, who it creates value for, and how it relates to the broader CitizenOnboard project.

We have three distinct use cases we want to serve, pretty well outlined by [Jake over on the original Project Ideas thread](https://github.com/codeforamerica/project-ideas/issues/43#issuecomment-66513479). They are, roughly:
- **Empower advocates with knowledge about whether the service is down**. This project was inspired by an enrollment event (with dozens of people involved) that was torpedoed by MBCW going down. We never want that to happen again—we want to notify enrollment assisters when sites are down. This page will introduce this audience the project, and let them know how they can subscribe to email and SMS updates.
- **Draw public attention to the problem**. When Healthcare.gov was down, the whole country paid attention. That kind of delivery crisis is ongoing across social services, in almost every state. We want to tell this story, in a way that is easily adopted and shared by media outlets. Media attention with drive awareness and social pressure to make improving uptime a priority for those in charge. We need to be deliberate in our messaging and the media assets that will spread.
- **Give people in charge a tool for tracking their progress**. We want to establish a standard that state departments and vendors should adhere to—something like 95% uptime. Which of course is a laughably low standard. We want to give folks in charge at these organizations the ability monitor their performance historically, and comparatively against other services. We also want to point them to key resources.

I'll start to stub out issues for the following features and tasks, which flow from the use cases outlined above:
- We want to reveal the data from @pingometer to journalists and agency analysts in an elegant way.
- #36 Service-level (or "component" level in the language of @statuspage) pages with key historical datasets—we want decision-makers to have a page they can visit to track their progress.
- #37 An summary graphic or map that shows which services have been up less than 95% of the time over some recent period (a week? a day?). We want this single graphic to communicate what we are doing, the scale, and why its important. 
- #38 An executive summary and some key figures—and site copy generally.
- #38 Instructions targeted at CBOs and assisters that want to know the status of the services they depend on and how to advocate for improved uptime—for example, subscribing to individual components via StatusPage is currently non-trivial.

cc @lippytak @Mr0grog @daguar @mollymcleod @bengolder

**Comment by Mr0grog** [comment]
So… as a quick afternoon test of just using Pingometer's API for something, I give you http://snap-status.herokuapp.com/ (powered by https://github.com/Mr0grog/snap-status).

It’s just a bit of JS that draws a map of the US, coloring states by up/down/we-don’t-know:
![snap-status](https://cloud.githubusercontent.com/assets/74178/5812209/d3fb0496-a019-11e4-85a6-9b4b48f73f83.png)

Not remotely something useful or final, but a start. I’ll work on this on-and-off, but anybody feel free to run with it, too.

**Comment by alanjosephwilliams** [comment]
So rad. A most excellent beginning to a very simple but very moving visualization. You have rendered visible some gaping holes in the safety net.

**Comment by Mr0grog** [comment]
Just made a quick update to show paused monitors (e.g. North Carolina) as gray. In so doing, I noticed that something is up with North Dakota, too. It’s not paused, but also doesn’t seem to be working (i.e. it’s not showing as down; Pingometer is showing no checks/events/etc. at all).

Also, checking the URL we have for it (https://apps.nd.gov/dhs/ea/oasys/main.html) shows a 404 (which, at first glance, is not obviously a 404). Maybe that’s the problem. Either way, seems like the monitor for ND might be configured wrong.

**Comment by pingometer** [comment]
@Mr0grog Can test the monitor for North Dakota now? This is one of the sites that requires a transaction monitor (to simulate a browser session). We took care of that on our end.

**Comment by pingometer** [comment]
@Mr0grog Also, we updated the URL to "https://apps.nd.gov/dhs/ea/oasys/login.htm" with a test for "Login" in the page content. This page, at least, doesn't 404 for now.

**Comment by Mr0grog** [comment]
@pingometer Ah, thanks! Looks like it’s working now. The site is actually pulling directly from your API on every request (obviously there should _probably_ be some caching involved in the future), so you can just look at it to see if it’s working as expected :)

**Comment by pingometer** [comment]
Looks good here! If you need us to roll up our sleeves for anything, we're up for a challenge. :)

**Comment by lippytak** [comment]
v1 is going is going to be a point in time essay, so let's move the discussion here: https://github.com/codeforamerica/snap-it-up/issues/6
