### ISSUE TITLE
Regularly retrieve historical uptime for each service from Pingometer API

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/citizen-onboard#37]
We want to create a map or chart that can communicate in a single image the recent uptime for all SNAP services. To do this, we'll need to query the Pingometer API on an ongoing basis.

**Comment by lippytak** [comment]
Pingometer actually maintains the full status of all checks and events (when checks change the status) so no need for us to do this unless I'm missing something.

**Comment by alanjosephwilliams** [comment]
Nice, I'll close for now and we can be more specific about implementation when we open up new issues
