### ISSUE TITLE
StatusBoard Page site copy

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/citizen-onboard#38]
- [ ] Executive Summary / Narrative
- [ ] Key figures
- [ ] Instruction for subscriptions
- [ ] Section for journalists and data analysts
- [ ] Section for decision-makers
- [ ] Section for assisters

---
- [ ] Update main CitizenOnboard homepage to reflect this new component of the project.

**Comment by lippytak** [comment]
For v1 think we could do all of this via StatusPageio? You can add custom css/html so we could add project info and instructions to the header and just set the domain to status.citizenonboard.com?

**Comment by alanjosephwilliams** [comment]
It would be better if we could. However, creating individual pages for "components" in StatusPageio was non-obvious. If we are already creating custom pages for each state or component, we may want to create a consistent look and feel on the home/splash/introduction page.

**Comment by lippytak** [comment]
v1 is going is going to be a point in time essay, so let's move the discussion here: https://github.com/codeforamerica/snap-it-up/issues/6
