### ISSUE TITLE
Technical Write-up

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/citizen-onboard#41]
We need to thoughtfully articulate the approach we are taking to monitoring, the tradeoffs we are making, and perhaps even the alternatives considered—so that the project is defensible and transparent.

**Comment by alanjosephwilliams** [comment]
This could go in the wiki.

**Comment by lippytak** [comment]
v1 is going is going to be a point in time essay, so let's move the discussion here: https://github.com/codeforamerica/snap-it-up/issues/6
