### ISSUE TITLE
Get partners subscribed to CA monitors

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/citizen-onboard#45]
- [x] Team dog food for ~1 week with CA services to sanity check that alerts are accurateish
- [ ] Decide who we want to subscribe, prepare them for frequent alerts, and give them frame for understanding what this monitoring is.
- [ ] Decide what we want to learn in advance of broader exposure.

**Comment by lippytak** [comment]
Adding a bullet:
- [ ] Team dog food for ~1 week with CA services to sanity check that alerts are accurateish
