### ISSUE TITLE
Ship Jan teardown

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/citizen-onboard#48]
- Upload Molly's stuff
- Writeup a fun little announcement
- Review with molly + team
- ship

**Comment by lippytak** [comment]
Waiting for a any lingering feedback from @mollymcleod and @alanjosephwilliams before shipping (hopefully) tomorrow.

**Comment by alanjosephwilliams** [comment]
The teardown is great. Would love to see the e-mail before it ships.

On Mon, Feb 2, 2015 at 5:26 PM, Jake Solomon notifications@github.com
wrote:

> Waiting for a any lingering feedback from @mollymcleod
> https://github.com/mollymcleod and @alanjosephwilliams
> https://github.com/alanjosephwilliams before shipping (hopefully)
> tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/citizen-onboard/issues/48#issuecomment-72574906
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
This is done, yeah?

**Comment by daguar** [comment]
Oh, I guess only the upload is some, sorry!

**Comment by lippytak** [comment]
Done!
- The Teardown: citizenonboard.com/snap/wa
- The Tweet: https://twitter.com/CitizenOnboard/status/562719193817448449
- The TinyLetter: tinyletter.com/CitizenOnboard/letters/citizenonboard-how-washington-onboards-new-food-stamp-users
