### ISSUE TITLE
Should the homepage have the logo?

### ISSUE THREAD

**Issue by mollymcleod** [codeforamerica/citizen-onboard#52]
![co-logo](https://cloud.githubusercontent.com/assets/4099343/6024757/6209a846-ab82-11e4-8a3a-09a84490e77b.gif)

https://github.com/codeforamerica/citizen-onboard/blob/gh-pages/img/CO-logo.gif

**Comment by lippytak** [comment]
Yes thanks :)

**Comment by lippytak** [comment]
Fixed
